"""
Market Basket Analysis — Apriori association-rule mining over a (basket ID,
item) column pair. Answers the classic retail/product-analytics question
"what gets bought together" via frequent itemsets and support/confidence/
lift-scored association rules (e.g. "customers who buy Bread also buy
Milk 78% of the time, 2.3x more often than chance").

Implemented from scratch (no `mlxtend` dependency) with the standard
Apriori join-and-prune algorithm (Agrawal & Srikant 1994): start from
frequent single items, then repeatedly generate size-(k+1) candidates by
joining frequent size-k itemsets and pruning any candidate whose subsets
aren't themselves frequent (the "apriori property" — a superset of an
infrequent itemset can't be frequent), counting each level's candidates
against the transaction data. Bounded to itemsets of size <= 3
(MAX_ITEMSET_SIZE) — most actionable "bought together" insight lives in
pairs and triples; deeper itemsets are rare and expensive for a UI tool.

Two tractability caps protect against pathological inputs (thousands of
distinct items or gigantic transaction logs), both reported back so the
caller can tell the user their result may be a sample/truncation:
  - MAX_DISTINCT_ITEMS: only the most frequent N items are considered
    for itemsets past the first level (a long tail of rare items would
    blow up the O(L1^2) candidate-pair generation for no analytical gain
    at the default 1% support floor).
  - MAX_BASKETS: baskets are randomly sampled down to this count before
    mining (support/confidence/lift are still statistically meaningful
    on a large-enough sample; the alternative is not finishing at all).
"""

from __future__ import annotations

import random
from collections import Counter
from itertools import combinations
from typing import Optional

import pandas as pd
import plotly.express as px

MAX_ITEMSET_SIZE = 3
MAX_DISTINCT_ITEMS = 200
MAX_BASKETS = 50_000
MIN_BASKETS = 10

# Candidate itemsets are generated by joining pairs of frequent itemsets
# from the previous level (O(n^2) in how many are frequent) — cap how many
# survive to the next level, keeping the highest-support ones, so a
# low-support-floor run on a huge item vocabulary can't blow up runtime.
MAX_FREQUENT_PER_LEVEL = 500

# A basket with more distinct items than this contributes only a random
# MAX_BASKET_ITEMS-sized sample of its items to itemset counting past size
# 1 — real retail baskets are rarely this large; this only guards the
# pathological case (e.g. a basket ID that isn't really a basket).
MAX_BASKET_ITEMS = 40


def build_transactions(df: pd.DataFrame, basket_col: str, item_col: str) -> list[frozenset]:
    """Group (basket_col, item_col) rows into one frozenset of item names
    per distinct basket. Drops rows with a missing basket or item value;
    duplicate items within the same basket collapse to one (Apriori works
    on item presence, not repeat-purchase counts).
    """
    clean = df[[basket_col, item_col]].dropna()
    if clean.empty:
        return []
    grouped = clean.groupby(basket_col)[item_col].apply(lambda s: frozenset(s.astype(str)))
    return [items for items in grouped.tolist() if items]


def _generate_candidates(frequent_itemsets: list[frozenset], k: int) -> set[frozenset]:
    """Apriori join + prune: join pairs of frequent size-(k-1) itemsets that
    together span exactly k items, keeping only candidates all of whose
    size-(k-1) subsets are themselves frequent (a size-k itemset can't be
    frequent if any of its subsets isn't — the apriori property).
    """
    frequent_set = set(frequent_itemsets)
    ordered = sorted(frequent_itemsets, key=lambda s: sorted(s))
    candidates: set[frozenset] = set()
    n = len(ordered)
    for i in range(n):
        for j in range(i + 1, n):
            union = ordered[i] | ordered[j]
            if len(union) != k:
                continue
            if all(frozenset(union - {item}) in frequent_set for item in union):
                candidates.add(union)
    return candidates


def find_frequent_itemsets(
    transactions: list[frozenset],
    min_support: float,
    max_itemset_size: int = MAX_ITEMSET_SIZE,
    max_distinct_items: int = MAX_DISTINCT_ITEMS,
) -> tuple[dict[frozenset, tuple[float, int]], int]:
    """Classic Apriori over `transactions` (one frozenset of items per
    basket). Returns ({itemset: (support, count)}, n_transactions) for
    every itemset from size 1 up to max_itemset_size meeting min_support.

    Counting at each level walks each transaction's own item combinations
    (bounded by that basket's size, capped at MAX_BASKET_ITEMS) rather than
    checking every candidate against every transaction — the standard way
    to keep Apriori counting tractable when the candidate set is large.
    """
    n = len(transactions)
    if n == 0:
        return {}, 0

    item_counts = Counter()
    for t in transactions:
        item_counts.update(t)

    kept_items = {item for item, _ in item_counts.most_common(max_distinct_items)}
    trimmed = []
    rng = random.Random(42)
    for t in transactions:
        restricted = t & kept_items
        if len(restricted) > MAX_BASKET_ITEMS:
            restricted = frozenset(rng.sample(sorted(restricted), MAX_BASKET_ITEMS))
        trimmed.append(restricted)

    level_frequent = {
        frozenset([item]): count for item, count in item_counts.items()
        if item in kept_items and count / n >= min_support
    }
    all_frequent = dict(level_frequent)

    k = 2
    while level_frequent and k <= max_itemset_size:
        level_keys = list(level_frequent.keys())
        if len(level_keys) > MAX_FREQUENT_PER_LEVEL:
            level_keys = sorted(level_keys, key=lambda fs: level_frequent[fs], reverse=True)[:MAX_FREQUENT_PER_LEVEL]

        candidates = _generate_candidates(level_keys, k)
        if not candidates:
            break

        counts: Counter = Counter()
        for t in trimmed:
            if len(t) < k:
                continue
            for combo in combinations(sorted(t), k):
                fs = frozenset(combo)
                if fs in candidates:
                    counts[fs] += 1

        level_frequent = {fs: cnt for fs, cnt in counts.items() if cnt / n >= min_support}
        all_frequent.update(level_frequent)
        k += 1

    return {fs: (cnt / n, cnt) for fs, cnt in all_frequent.items()}, n


def compute_association_rules(
    df: pd.DataFrame,
    basket_col: str,
    item_col: str,
    min_support: float = 0.01,
    min_confidence: float = 0.3,
    max_itemset_size: int = MAX_ITEMSET_SIZE,
    max_distinct_items: int = MAX_DISTINCT_ITEMS,
    max_baskets: int = MAX_BASKETS,
) -> dict:
    """End-to-end: build transactions, mine frequent itemsets, derive
    association rules (antecedent -> consequent) for every frequent
    itemset of size >= 2, scored by support/confidence/lift, filtered to
    confidence >= min_confidence.

    Returns a dict with "rules" (DataFrame, sorted by lift descending),
    "frequent_itemsets" (DataFrame, sorted by support descending),
    "n_baskets" (baskets actually mined, post-sampling), "n_baskets_total"
    (before sampling), "n_distinct_items", and "sampled" (bool) — or
    "error" if the inputs can't support rule mining at all. A result with
    frequent itemsets but zero rules meeting min_confidence is NOT an
    error — "rules" is just an empty DataFrame, so the itemsets are still
    shown with a "try lowering min_confidence" hint.
    """
    if basket_col == item_col:
        return {"error": "Basket ID and Item columns must be different columns."}

    clean = df[[basket_col, item_col]].dropna()
    if clean.empty:
        return {"error": "No complete (Basket ID, Item) rows available — both columns had missing values."}

    n_baskets_total = int(clean[basket_col].nunique())
    if n_baskets_total < MIN_BASKETS:
        return {
            "error": (
                f"Only {n_baskets_total} basket(s) available — need at least {MIN_BASKETS} "
                "distinct baskets to mine association rules reliably."
            )
        }

    n_distinct_items = int(clean[item_col].nunique())

    transactions = build_transactions(clean, basket_col, item_col)
    sampled = False
    if len(transactions) > max_baskets:
        transactions = random.Random(42).sample(transactions, max_baskets)
        sampled = True

    frequent, n = find_frequent_itemsets(transactions, min_support, max_itemset_size, max_distinct_items)
    if not frequent:
        return {
            "error": (
                f"No itemsets met the minimum support of {min_support:.1%} across {n} basket(s) — "
                "try lowering the minimum support."
            )
        }

    support_lookup = {fs: sup for fs, (sup, _cnt) in frequent.items()}

    rules = []
    for itemset, (support, count) in frequent.items():
        if len(itemset) < 2:
            continue
        for r in range(1, len(itemset)):
            for antecedent_items in combinations(sorted(itemset), r):
                antecedent = frozenset(antecedent_items)
                consequent = itemset - antecedent
                antecedent_support = support_lookup.get(antecedent)
                consequent_support = support_lookup.get(consequent)
                if not antecedent_support or not consequent_support:
                    continue
                confidence = support / antecedent_support
                if confidence < min_confidence:
                    continue
                lift = confidence / consequent_support
                rules.append(
                    {
                        "antecedent": ", ".join(sorted(antecedent)),
                        "consequent": ", ".join(sorted(consequent)),
                        "support": round(support, 4),
                        "confidence": round(confidence, 4),
                        "lift": round(lift, 4),
                        "count": count,
                    }
                )

    rules_df = pd.DataFrame(rules, columns=["antecedent", "consequent", "support", "confidence", "lift", "count"])
    if not rules_df.empty:
        rules_df = rules_df.sort_values("lift", ascending=False).reset_index(drop=True)

    itemsets_df = pd.DataFrame(
        [
            {"itemset": ", ".join(sorted(fs)), "size": len(fs), "support": round(sup, 4), "count": cnt}
            for fs, (sup, cnt) in frequent.items()
        ],
        columns=["itemset", "size", "support", "count"],
    ).sort_values("support", ascending=False).reset_index(drop=True)

    return {
        "rules": rules_df,
        "frequent_itemsets": itemsets_df,
        "n_baskets": n,
        "n_baskets_total": n_baskets_total,
        "n_distinct_items": n_distinct_items,
        "sampled": sampled,
    }


def rule_verdict(lift: float) -> str:
    """Plain-English read of a rule's lift — how much more likely the
    consequent is when the antecedent is present, vs. its base rate.
    """
    if lift >= 3:
        return f"Lift {lift:.2f} — very strong association, well beyond chance."
    if lift >= 1.5:
        return f"Lift {lift:.2f} — meaningfully more likely together than independently."
    if lift > 1.0:
        return f"Lift {lift:.2f} — slightly more likely together than chance would predict."
    if lift == 1.0:
        return "Lift 1.00 — no association; items appear together exactly as often as chance predicts."
    return f"Lift {lift:.2f} — appear together LESS often than chance would predict."


def build_rules_chart(rules_df: pd.DataFrame, top_n: int = 15) -> px.Figure:
    """Horizontal bar chart of the top rules by lift, labeled
    'antecedent -> consequent'."""
    if rules_df.empty:
        fig = px.bar(title="Association Rules (by lift)")
        fig.update_layout(margin=dict(t=50, b=10, l=10, r=10))
        return fig

    top = rules_df.head(top_n).copy()
    top["rule"] = top["antecedent"] + " → " + top["consequent"]
    top = top.iloc[::-1]  # so the highest-lift rule plots at the top

    fig = px.bar(
        top, x="lift", y="rule", orientation="h",
        labels={"lift": "Lift", "rule": ""}, title="Top Association Rules (by lift)",
        hover_data=["support", "confidence", "count"],
    )
    fig.update_layout(margin=dict(t=50, b=10, l=10, r=10))
    return fig
