"""
Report — renders the current data quality summary + charts + stats into a
single self-contained HTML file the user can download and share.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

import pandas as pd
import plotly.graph_objects as go

REPORT_CSS = """
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #0a0e17; color: #e0f7fa; padding: 2rem; }
  h1 { color: #00e5ff; border-bottom: 2px solid #00e5ff; padding-bottom: 0.5rem; }
  h2 { color: #00e5ff; margin-top: 2.5rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #26344a; padding: 6px 10px; text-align: left; font-size: 0.9rem; }
  th { background: #111827; color: #00e5ff; }
  tr:nth-child(even) { background: #0f1520; }
  .metric-row { display: flex; gap: 2rem; flex-wrap: wrap; margin: 1rem 0; }
  .metric { background: #111827; border: 1px solid #26344a; border-radius: 8px; padding: 1rem 1.5rem; }
  .metric .value { font-size: 1.6rem; color: #00e5ff; font-weight: 600; }
  .metric .label { font-size: 0.85rem; color: #9fb3c8; }
  .footer { margin-top: 3rem; color: #6b7d94; font-size: 0.8rem; }
</style>
"""


def _quality_section_html(quality_report: dict) -> str:
    metrics = [
        ("Rows", f"{quality_report['n_rows']:,}"),
        ("Columns", quality_report["n_cols"]),
        ("Duplicate Rows", quality_report["duplicate_rows"]),
        ("Missing Cells", f"{quality_report['total_missing_pct']}%"),
        ("Memory Usage", quality_report["memory_usage"]),
    ]
    metric_html = "".join(
        f'<div class="metric"><div class="value">{v}</div><div class="label">{label}</div></div>'
        for label, v in metrics
    )

    missing_rows = "".join(
        f"<tr><td>{col}</td><td>{pct}%</td></tr>"
        for col, pct in quality_report["missing_by_column"].items()
        if pct > 0
    )
    missing_table = (
        f"<table><tr><th>Column</th><th>Missing %</th></tr>{missing_rows}</table>"
        if missing_rows
        else "<p>No missing values detected.</p>"
    )

    outlier_rows = "".join(
        f"<tr><td>{col}</td><td>{info['count']}</td><td>{info['pct']}%</td></tr>"
        for col, info in quality_report["outliers"].items()
        if info["count"] > 0
    )
    outlier_table = (
        f"<table><tr><th>Column</th><th>Outlier Count</th><th>Outlier %</th></tr>{outlier_rows}</table>"
        if outlier_rows
        else "<p>No outliers detected via the IQR method.</p>"
    )

    return f"""
    <h2>Data Quality Summary</h2>
    <div class="metric-row">{metric_html}</div>
    <h3>Missing Values by Column</h3>
    {missing_table}
    <h3>Outliers (IQR method)</h3>
    {outlier_table}
    """


def generate_html_report(
    df: pd.DataFrame,
    quality_report: dict,
    stats_df: pd.DataFrame,
    charts: dict[str, go.Figure],
    cleaning_log: Optional[list[str]] = None,
) -> str:
    """Assemble the full standalone HTML report string."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    cleaning_html = ""
    if cleaning_log:
        items = "".join(f"<li>{step}</li>" for step in cleaning_log)
        cleaning_html = f"<h2>Cleaning Steps Applied</h2><ul>{items}</ul>"

    stats_html = f"<h2>Summary Statistics</h2>{stats_df.to_html(classes='stats-table')}"

    charts_html_parts = []
    for i, (title, fig) in enumerate(charts.items()):
        include_js = "cdn" if i == 0 else False
        charts_html_parts.append(f"<h2>{title}</h2>")
        charts_html_parts.append(fig.to_html(full_html=False, include_plotlyjs=include_js))
    charts_html = "".join(charts_html_parts)

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Prism Auto-EDA Report</title>
  {REPORT_CSS}
</head>
<body>
  <h1>Prism — Auto-EDA Report</h1>
  <p>Generated {generated_at} &middot; {df.shape[0]:,} rows &times; {df.shape[1]} columns</p>
  {_quality_section_html(quality_report)}
  {cleaning_html}
  {stats_html}
  {charts_html}
  <div class="footer">Generated by Prism — an Auto-EDA tool with an AI analyst layer.</div>
</body>
</html>"""
