"""
Report — renders the current data quality summary + charts + stats into a
single self-contained HTML file the user can download and share.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

import pandas as pd
import plotly.graph_objects as go

# Standalone exported artifact — always rendered in Prism's default
# "Graphite" palette regardless of which theme was active in the live app,
# so a shared report looks the same for every recipient.
REPORT_CSS = """
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
  body {
    font-family: 'Inter', 'Segoe UI', Arial, sans-serif;
    background: linear-gradient(180deg, #0A0C10 0%, #0D1016 100%);
    color: #F1F5F9;
    padding: 2.5rem;
    max-width: 1100px;
    margin: 0 auto;
  }
  h1 { color: #F1F5F9; font-weight: 800; letter-spacing: -0.02em; border-bottom: 2px solid #22D3EE; padding-bottom: 0.6rem; }
  h2 { color: #22D3EE; font-weight: 700; margin-top: 2.75rem; }
  h3 { color: #F1F5F9; font-weight: 600; }
  p { color: #8A97A8; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; border-radius: 10px; overflow: hidden; }
  th, td { border: 1px solid #232833; padding: 8px 12px; text-align: left; font-size: 0.9rem; }
  th { background: #12151B; color: #22D3EE; font-weight: 600; }
  tr:nth-child(even) { background: #12151B; }
  .metric-row { display: flex; gap: 1rem; flex-wrap: wrap; margin: 1rem 0; }
  .metric { background: #12151B; border: 1px solid #232833; border-radius: 12px; padding: 1rem 1.5rem; }
  .metric .value { font-size: 1.6rem; color: #22D3EE; font-weight: 700; }
  .metric .label { font-size: 0.82rem; color: #8A97A8; }
  .footer { margin-top: 3rem; color: #8A97A8; font-size: 0.8rem; border-top: 1px solid #232833; padding-top: 1.25rem; }
</style>
"""


def _quality_section_html(quality_report: dict) -> str:
    metrics = [
        ("Rows", f"{quality_report['n_rows']:,}"),
        ("Columns", quality_report["n_cols"]),
        ("Duplicate Rows", quality_report["duplicate_rows"]),
        ("Missing Cells", f"{quality_report['total_missing_pct']}%"),
        ("Memory Usage", quality_report["memory_usage"]),
    ]
    metric_html = "".join(
        f'<div class="metric"><div class="value">{v}</div><div class="label">{label}</div></div>'
        for label, v in metrics
    )

    missing_rows = "".join(
        f"<tr><td>{col}</td><td>{pct}%</td></tr>"
        for col, pct in quality_report["missing_by_column"].items()
        if pct > 0
    )
    missing_table = (
        f"<table><tr><th>Column</th><th>Missing %</th></tr>{missing_rows}</table>"
        if missing_rows
        else "<p>No missing values detected.</p>"
    )

    outlier_rows = "".join(
        f"<tr><td>{col}</td><td>{info['count']}</td><td>{info['pct']}%</td></tr>"
        for col, info in quality_report["outliers"].items()
        if info["count"] > 0
    )
    outlier_table = (
        f"<table><tr><th>Column</th><th>Outlier Count</th><th>Outlier %</th></tr>{outlier_rows}</table>"
        if outlier_rows
        else "<p>No outliers detected via the IQR method.</p>"
    )

    return f"""
    <h2>Data Quality Summary</h2>
    <div class="metric-row">{metric_html}</div>
    <h3>Missing Values by Column</h3>
    {missing_table}
    <h3>Outliers (IQR method)</h3>
    {outlier_table}
    """


def generate_html_report(
    df: pd.DataFrame,
    quality_report: dict,
    stats_df: pd.DataFrame,
    charts: dict[str, go.Figure],
    cleaning_log: Optional[list[str]] = None,
) -> str:
    """Assemble the full standalone HTML report string."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    cleaning_html = ""
    if cleaning_log:
        items = "".join(f"<li>{step}</li>" for step in cleaning_log)
        cleaning_html = f"<h2>Cleaning Steps Applied</h2><ul>{items}</ul>"

    stats_html = f"<h2>Summary Statistics</h2>{stats_df.to_html(classes='stats-table')}"

    charts_html_parts = []
    for i, (title, fig) in enumerate(charts.items()):
        include_js = "cdn" if i == 0 else False
        charts_html_parts.append(f"<h2>{title}</h2>")
        charts_html_parts.append(fig.to_html(full_html=False, include_plotlyjs=include_js))
    charts_html = "".join(charts_html_parts)

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Prism Auto-EDA Report</title>
  {REPORT_CSS}
</head>
<body>
  <h1>Prism — Auto-EDA Report</h1>
  <p>Generated {generated_at} &middot; {df.shape[0]:,} rows &times; {df.shape[1]} columns</p>
  {_quality_section_html(quality_report)}
  {cleaning_html}
  {stats_html}
  {charts_html}
  <div class="footer">Generated by Prism — an Auto-EDA tool with an AI analyst layer.</div>
</body>
</html>"""
